"""
app/api/v1/auth.py

Authentication endpoints:
  POST /v1/auth/signup        — Create account with invite code
  POST /v1/auth/login         — Login (email + password)
  POST /v1/auth/login/key     — Login with API key (programmatic)
  POST /v1/auth/refresh       — Refresh access token
  GET  /v1/auth/me            — Current user info
  GET  /v1/auth/invite/verify — Verify invite code (public, for UI validation)
"""

from __future__ import annotations

import hashlib
import secrets
from datetime import datetime, timezone
from uuid import UUID, uuid4

import bcrypt
import structlog
from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, EmailStr, Field
from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.api.middleware.jwt_auth import (
    create_access_token,
    create_refresh_token,
    decode_token,
)
from app.db.models import ApiKeyRecord, UserRecord, OrganizationRecord, InviteCodeRecord
from app.dependencies import get_db_session
from app.models.domain import AuthContext
from app.api.middleware.auth import get_auth_context
from app.db.repository import AuditRepository
from config import get_settings

logger = structlog.get_logger(__name__)

router = APIRouter(tags=["authentication"])


# ── Password Utilities ─────────────────────────────────

def hash_password(password: str) -> str:
    return bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")


def verify_password(password: str, password_hash: str) -> bool:
    return bcrypt.checkpw(password.encode("utf-8"), password_hash.encode("utf-8"))


# ── Request/Response Models ────────────────────────────

class SignupRequest(BaseModel):
    email: EmailStr
    password: str = Field(min_length=8, max_length=128)
    name: str = Field(min_length=1, max_length=200)
    invite_code: str = Field(
        min_length=3, max_length=20,
        description="Invite code from your organization admin",
        examples=["INV-a8f3b2c1"],
    )


class LoginRequest(BaseModel):
    email: EmailStr
    password: str = Field(min_length=1)


class ApiKeyLoginRequest(BaseModel):
    api_key: str = Field(min_length=10)


class TokenResponse(BaseModel):
    access_token: str
    refresh_token: str
    token_type: str = "bearer"
    expires_in: int
    user: UserInfo


class UserInfo(BaseModel):
    user_id: str
    email: str
    name: str
    role: str
    org_id: str
    org_name: str
    is_superadmin: bool = False


class RefreshRequest(BaseModel):
    refresh_token: str


class RefreshResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    expires_in: int


class InviteVerifyResponse(BaseModel):
    valid: bool
    org_name: str | None = None
    role: str | None = None
    message: str


TokenResponse.model_rebuild()


# ── Endpoints ──────────────────────────────────────────

@router.get("/auth/invite/verify", response_model=InviteVerifyResponse)
async def verify_invite_code(
    code: str = Query(min_length=3, max_length=20),
    session: AsyncSession = Depends(get_db_session),
):
    """
    Verify an invite code before signup.
    Public endpoint — no auth required.
    Used by the frontend to show org name and validate code in real-time.
    """
    result = await session.execute(
        select(InviteCodeRecord)
        .options(selectinload(InviteCodeRecord.organization))
        .where(InviteCodeRecord.code == code)
    )
    invite = result.scalar_one_or_none()

    if invite is None:
        return InviteVerifyResponse(valid=False, message="Invalid invite code")

    if not invite.is_active:
        return InviteVerifyResponse(valid=False, message="Invite code has been deactivated")

    if invite.times_used >= invite.max_uses:
        return InviteVerifyResponse(valid=False, message="Invite code has reached maximum uses")

    if invite.expires_at < datetime.now(timezone.utc):
        return InviteVerifyResponse(valid=False, message="Invite code has expired")

    return InviteVerifyResponse(
        valid=True,
        org_name=invite.organization.name,
        role=invite.role,
        message=f"Valid! You'll join '{invite.organization.name}' as {invite.role}",
    )


@router.post("/auth/signup", response_model=TokenResponse)
async def signup(
    request: SignupRequest,
    session: AsyncSession = Depends(get_db_session),
):
    """
    Create a new user account using an invite code.

    The invite code determines:
      - Which organization the user joins
      - What role they get (viewer/editor)

    Invite codes are generated by org admins.
    """
    settings = get_settings()

    # ── Validate invite code ───────────────────────────
    result = await session.execute(
        select(InviteCodeRecord)
        .options(selectinload(InviteCodeRecord.organization))
        .where(InviteCodeRecord.code == request.invite_code)
    )
    invite = result.scalar_one_or_none()

    if invite is None:
        raise HTTPException(status_code=400, detail="Invalid invite code")

    # Explicit validation checks (don't rely on property)
    if not invite.is_active:
        raise HTTPException(status_code=400, detail="Invite code has been deactivated")

    if invite.expires_at < datetime.now(timezone.utc):
        raise HTTPException(status_code=400, detail="Invite code has expired")

    if invite.times_used >= invite.max_uses:
        raise HTTPException(status_code=400, detail=f"Invite code has reached maximum uses ({invite.max_uses})")

    if not invite.organization.is_active:
        raise HTTPException(status_code=400, detail="Organization is disabled")

    org = invite.organization
    if not org.is_active:
        raise HTTPException(status_code=400, detail="Organization is disabled")

    # ── Check email uniqueness ─────────────────────────
    existing = await session.execute(
        select(UserRecord).where(UserRecord.email == request.email)
    )
    if existing.scalar_one_or_none():
        raise HTTPException(status_code=409, detail="Email already registered")

    # ── Create user ────────────────────────────────────
    user_id = uuid4()
    user = UserRecord(
        id=user_id,
        org_id=org.id,
        email=request.email,
        name=request.name,
        password_hash=hash_password(request.password),
        role=invite.role,
        is_active=True,
    )
    session.add(user)

    # ── Auto-generate API key ──────────────────────────
    raw_key = "qf-" + secrets.token_urlsafe(32)
    key_hash = hashlib.sha256(raw_key.encode()).hexdigest()
    api_key = ApiKeyRecord(
        id=uuid4(),
        org_id=org.id,
        user_id=user_id,
        key_hash=key_hash,
        key_prefix=raw_key[:8],
        name=f"Default key for {request.email}",
        is_active=True,
    )
    session.add(api_key)

    # ── Increment invite usage ─────────────────────────
    await session.execute(
        update(InviteCodeRecord)
        .where(InviteCodeRecord.id == invite.id)
        .values(times_used=InviteCodeRecord.times_used + 1)
    )

    # ── Audit log ──────────────────────────────────────
    audit = AuditRepository(session)
    await audit.log(
        action="user_signup",
        user_id=user_id,
        org_id=org.id,
        detail={
            "email": request.email,
            "role": invite.role,
            "org_name": org.name,
            "invite_code": request.invite_code,
        },
    )

    await session.commit()

    # ── Generate JWT tokens ────────────────────────────
    access_token = create_access_token(
        user_id=user_id, org_id=org.id, email=request.email, role=invite.role,is_superadmin=user.is_superadmin,
    )
    refresh_token = create_refresh_token(user_id=user_id)

    logger.info(
        "user_signed_up",
        user_id=str(user_id),
        email=request.email,
        org=org.name,
        role=invite.role,
        invite_code=request.invite_code,
    )

    return TokenResponse(
        access_token=access_token,
        refresh_token=refresh_token,
        expires_in=settings.jwt_access_token_hours * 3600,
        user=UserInfo(
            user_id=str(user_id),
            email=request.email,
            name=request.name,
            role=invite.role,
            org_id=str(org.id),
            org_name=org.name,
            is_superadmin=user.is_superadmin,
        ),
    )


@router.post("/auth/login", response_model=TokenResponse)
async def login(
    request: LoginRequest,
    session: AsyncSession = Depends(get_db_session),
):
    """Login with email and password."""
    settings = get_settings()

    result = await session.execute(
        select(UserRecord)
        .options(selectinload(UserRecord.organization))
        .where(UserRecord.email == request.email)
    )
    user = result.scalar_one_or_none()

    if user is None:
        raise HTTPException(status_code=401, detail="Invalid email or password")

    if not user.is_active:
        raise HTTPException(status_code=403, detail="Account is disabled")

    if not user.organization.is_active:
        raise HTTPException(status_code=403, detail="Organization is disabled")

    if not user.password_hash:
        raise HTTPException(status_code=401, detail="No password set. Contact your admin.")

    if not verify_password(request.password, user.password_hash):
        audit = AuditRepository(session)
        await audit.log(
            action="auth_failure",
            user_id=user.id,
            org_id=user.org_id,
            detail={"email": request.email, "reason": "wrong_password"},
        )
        await session.commit()
        raise HTTPException(status_code=401, detail="Invalid email or password")

    access_token = create_access_token(
        user_id=user.id, org_id=user.org_id, email=user.email, role=user.role,is_superadmin=user.is_superadmin,
    )
    refresh_token = create_refresh_token(user_id=user.id)

    audit = AuditRepository(session)
    await audit.log(
        action="auth_success",
        user_id=user.id,
        org_id=user.org_id,
        detail={"email": request.email, "method": "password"},
    )
    await session.commit()

    return TokenResponse(
        access_token=access_token,
        refresh_token=refresh_token,
        expires_in=settings.jwt_access_token_hours * 3600,
        user=UserInfo(
            user_id=str(user.id),
            email=user.email,
            name=user.name,
            role=user.role,
            org_id=str(user.org_id),
            org_name=user.organization.name,
            is_superadmin=user.is_superadmin,
        ),
    )


@router.post("/auth/login/key", response_model=TokenResponse)
async def login_with_api_key(
    request: ApiKeyLoginRequest,
    session: AsyncSession = Depends(get_db_session),
):
    """Login with API key (programmatic access)."""
    settings = get_settings()

    key_hash = hashlib.sha256(request.api_key.encode()).hexdigest()

    result = await session.execute(
        select(ApiKeyRecord)
        .options(selectinload(ApiKeyRecord.user).selectinload(UserRecord.organization))
        .where(ApiKeyRecord.key_hash == key_hash, ApiKeyRecord.is_active == True)
    )
    api_key_record = result.scalar_one_or_none()

    if api_key_record is None:
        raise HTTPException(status_code=401, detail="Invalid API key")

    user = api_key_record.user
    org = user.organization

    if not user.is_active:
        raise HTTPException(status_code=403, detail="User account is disabled")
    if not org.is_active:
        raise HTTPException(status_code=403, detail="Organization is disabled")

    access_token = create_access_token(
        user_id=user.id, org_id=org.id, email=user.email, role=user.role,is_superadmin=user.is_superadmin,
    )
    refresh_token = create_refresh_token(user_id=user.id)

    return TokenResponse(
        access_token=access_token,
        refresh_token=refresh_token,
        expires_in=settings.jwt_access_token_hours * 3600,
        user=UserInfo(
            user_id=str(user.id), email=user.email, name=user.name,
            role=user.role, org_id=str(user.org_id), org_name=org.name,
            is_superadmin=user.is_superadmin,
        ),
    )


@router.post("/auth/refresh", response_model=RefreshResponse)
async def refresh_token(
    request: RefreshRequest,
    session: AsyncSession = Depends(get_db_session),
):
    settings = get_settings()
    payload = decode_token(request.refresh_token)

    if payload.get("type") != "refresh":
        raise HTTPException(status_code=401, detail="Expected refresh token")

    result = await session.execute(
        select(UserRecord)
        .options(selectinload(UserRecord.organization))
        .where(UserRecord.id == UUID(payload["sub"]), UserRecord.is_active == True)
    )
    user = result.scalar_one_or_none()

    if user is None:
        raise HTTPException(status_code=401, detail="User not found or disabled")

    access_token = create_access_token(
        user_id=user.id,
        org_id=user.org_id,
        email=user.email,
        role=user.role,
        is_superadmin=user.is_superadmin,
    )

    return RefreshResponse(
        access_token=access_token,
        expires_in=settings.jwt_access_token_hours * 3600,
    )


@router.get("/auth/me")
async def get_current_user(auth: AuthContext = Depends(get_auth_context)):
    """Get current user info."""
    return {
        "user_id": str(auth.user_id),
        "org_id": str(auth.org_id),
        "email": auth.email,
        "role": auth.role,
    }