"""add is_superadmin to users

Revision ID: 27c1b2a7cb8e
Revises: e4a19f708148
Create Date: 2026-03-20 16:18:03.042426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c1b2a7cb8e'
down_revision: Union[str, None] = 'e4a19f708148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column with server_default first (so existing rows get False)
    op.add_column('users', sa.Column(
        'is_superadmin',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('false'),
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superadmin')
    # ### end Alembic commands ###