"""add invite_codes table

Revision ID: c5904709c8ce
Revises: ead86aa2ea2e
Create Date: 2026-03-19 23:36:30.395031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5904709c8ce'
down_revision: Union[str, None] = 'ead86aa2ea2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='Role assigned to users who use this code: viewer, editor'),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invite_codes_code', 'invite_codes', ['code'], unique=False)
    op.create_index('ix_invite_codes_org_id', 'invite_codes', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invite_codes_org_id', table_name='invite_codes')
    op.drop_index('ix_invite_codes_code', table_name='invite_codes')
    op.drop_table('invite_codes')
    # ### end Alembic commands ###