"""update invite_codes table

Revision ID: e4a19f708148
Revises: c5904709c8ce
Create Date: 2026-03-20 04:48:18.329902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a19f708148'
down_revision: Union[str, None] = 'c5904709c8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invite_codes', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Role assigned to users who use this code: viewer, editor',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invite_codes', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='Role assigned to users who use this code: viewer, editor',
               existing_nullable=False)
    # ### end Alembic commands ###